name: verify-json
on:
    push:
        branches:
            - main
jobs:
    schema-conform:
        name: Validate JSON
        runs-on: ubuntu-20.04
        steps:
            - name: Clone repository
              uses: actions/checkout@v2

            - name: Install Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
                  architecture: 'x64'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --no-cache-dir jsonschema

            - name: Validate JSON schema
              id: schema
              run: |
                  jsonschema --instance ${{ github.workspace }}/website/messages.json ${{ github.workspace }}/website/messages.schema.json
                  jsonschema --instance ${{ github.workspace }}/website/people.json ${{ github.workspace }}/website/people.schema.json

            - name: Check messages reference existing users
              if: steps.schema.conclusion == 'success'
              run: |
                  python3 ${{ github.workspace }}/website/ci/verify-json/references.py

            - name: Check people have pictures
              if: steps.schema.conclusion == 'success'
              run: |
                  python3 ${{ github.workspace }}/website/ci/verify-json/pictures.py
