name: verify-json
on: [push]
jobs:
    schema-conform:
        name: Validate JSON
        runs-on: ubuntu-20.04
        steps:
            - name: Clone repository
              uses: actions/checkout@v2

            - name: Install Python and dependencies
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
                  architecture: 'x64'
              run: |
                  python -m pip install --upgrade pip
                  pip install --no-cache-dir jsonschema

            - name: Validate JSON schema
              id: schema
              run: |
                  jsonschema --instance ${{ env.GITHUB_WORKSPACE }}/messages.json ${{ env.GITHUB_WORKSPACE }}/messages.schema.json
                  jsonschema --instance ${{ env.GITHUB_WORKSPACE }}/people.json ${{ env.GITHUB_WORKSPACE }}/people.schema.json

            - name: Check messages reference existing users
              if: steps.schema.conclusion == 'success'
              run: |
                  python3 ${{ env.GITHUB_WORKSPACE }}/ci/verify-json/references.py

            - name: Check people have pictures
              if: steps.schema.conclusion == 'success'
              run: |
                  python3 ${{ env.GITHUB_WORKSPACE }}/ci/verify-json/pictures.py
